language: scala

scala:
  - 2.13.0-M5
  - 2.12.8

jdk:
  - oraclejdk8
  - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
  - scala: 0.14.0-RC1
    script: sbt ++$TRAVIS_SCALA_VERSION compile
    after_success:

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
